# development
# services:
#   frontend:
#     build:
#       context: ./fe
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"
#     networks:
#       - app-network

#   backend:
#     build:
#       context: ./be
#       dockerfile: Dockerfile
#     ports:
#       - "8001:8001"
#     env_file:
#       - ./be/.env
#     depends_on:
#       - db
#     networks:
#       - app-network

#   db:
#     image: mysql:8.0
#     container_name: hr-mysql-container
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: 251625
#       MYSQL_DATABASE: playground
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   mysql-data:

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./be/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
