version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # EC2에서 80번 포트로 서비스
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    env_file:
      - ./be/.env
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: hr-mysql-container
    restart: always
    ports:
      - "3306:3306" # EC2에서 MySQL 접근 가능
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!
      MYSQL_DATABASE: playground_production
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
